spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api_secure
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: passcodepasswd
jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  databse: mysql
  database.platform: org.hibernate.dialect.MySQL5Dialect